# Generated by Django 3.2.12 on 2022-03-20 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddiesforstudies', '0004_alter_classes_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='name',
            new_name='title',
        ),
    ]
