# Generated by Django 4.0.3 on 2022-04-11 03:35

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('buddiesforstudies', '0006_jsondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', mapbox_location_field.models.LocationField(map_attrs={'center': (-78.5, 38.04)})),
                ('address', mapbox_location_field.models.AddressAutoHiddenField(default='', map_id='map')),
            ],
        ),
    ]
