# Generated by Django 4.0.3 on 2022-04-18 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddiesforstudies', '0007_toggled_classes'),
        ('buddiesforstudies', '0008_location'),
    ]

    operations = [
    ]
