# Generated by Django 4.0.3 on 2022-04-18 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddiesforstudies', '0011_rename_user_session_user_1_session_user_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='meet_location',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, related_name='meet_location', to='buddiesforstudies.location'),
            preserve_default=b'I01\n',
        ),
    ]
