# Generated by Django 4.0.3 on 2022-04-18 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buddiesforstudies', '0012_session_meet_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='user_1',
        ),
        migrations.RemoveField(
            model_name='session',
            name='user_2',
        ),
        migrations.AddField(
            model_name='location',
            name='user_2',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, related_name='user_2', to=settings.AUTH_USER_MODEL),
            preserve_default=b'I01\n',
        ),
    ]
