# Generated by Django 4.0.3 on 2022-04-18 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buddiesforstudies', '0013_remove_session_user_1_remove_session_user_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='user_1',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, related_name='user_1', to=settings.AUTH_USER_MODEL),
            preserve_default=b'I01\n',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
