# Generated by Django 4.0.3 on 2022-04-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddiesforstudies', '0014_location_user_1_delete_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='date',
            field=models.DateField(null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
