# Generated by Django 4.0.3 on 2022-04-29 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buddiesforstudies', '0016_location_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='user_3',
            field=models.ForeignKey(blank=b'I01\n', null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, related_name='user_3', to=settings.AUTH_USER_MODEL),
            preserve_default=b'I01\n',
        ),
    ]
