# Generated by Django 4.0.4 on 2022-04-30 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddiesforstudies', '0017_location_user_3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_info',
        ),
    ]
