# Generated by Django 4.0.4 on 2022-04-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddiesforstudies', '0019_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='match_students',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
