# Generated by Django 4.0.4 on 2022-04-30 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buddiesforstudies', '0020_alter_user_info_match_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='user_3',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, related_name='user_3', to=settings.AUTH_USER_MODEL),
        ),
    ]
