# Generated by Django 4.0.4 on 2022-04-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddiesforstudies', '0021_alter_location_user_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='match_students',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
