# Generated by Django 4.0.3 on 2022-05-01 22:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buddiesforstudies', '0022_alter_user_info_match_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='match_students',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
