# Generated by Django 4.0.3 on 2022-05-02 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddiesforstudies', '0023_location_users_alter_user_info_match_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='user_1',
        ),
        migrations.RemoveField(
            model_name='location',
            name='user_2',
        ),
        migrations.RemoveField(
            model_name='location',
            name='user_3',
        ),

    ]
