# Generated by Django 3.2 on 2022-05-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddiesforstudies', '0024_remove_location_user_1_remove_location_user_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(max_length=128)),
                ('chat_id', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['friendly_name'],
            },
        ),
        migrations.CreateModel(
            name='participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=128)),
                ('user_id', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['identity'],
            },
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(to='buddiesforstudies.participant', verbose_name='List of Chat Members'),
        ),
    ]
